### ISSUE TITLE
After BuildPack 8.7.0, JVM Launch Error in JRE 8

### ISSUE THREAD

**Issue by bungabear** [paketo-buildpacks/bellsoft-liberica#131]
## What happened?

* What were you attempting to do?
**Run a docker image built by bootBuildGradle with Gradle 7.1, Java 8 and Spring Boot 2.5.4.**

* What did you expect to happen?
**Successfully launch**

* What was the actual behavior? Please provide log output, if possible.
**JVM Error** 
**below is a log header and full log file [hs_err_pid1.log](https://github.com/paketo-buildpacks/bellsoft-liberica/files/7229202/hs_err_pid1.log)**
  ```
  #
  # A fatal error has been detected by the Java Runtime Environment:
  #
  #  SIGSEGV (0xb) at pc=0x00007f2fc8dc22f7, pid=1, tid=0x00007f2fc9f2a700
  #
  # JRE version:  (8.0_302-b08) (build )
  # Java VM: OpenJDK 64-Bit Server VM (25.302-b08 mixed mode linux-amd64 compressed oops)
  # Problematic frame:
  # V  [libjvm.so+0xb2a2f7]  VirtualMemoryTracker::add_reserved_region(unsigned char*, unsigned long, NativeCallStack const&, MemoryType, bool)+0x77
  #
  # Core dump written. Default location: /workspace/core or core.1
  #
  # If you would like to submit a bug report, please visit:
  #   https://bell-sw.com/support
  #
  ```

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
**I have no idea. I used only pure bootBuildImage**

* What buildpacks are you using? Please include versions.
  **A log of bootBuildImage with JVM errored verion,** 
[error_version_log.txt](https://github.com/paketo-buildpacks/bellsoft-liberica/files/7229211/error_version_log.txt)

  **A log of bootBuildImage at yesterday that successfully launched. and it is same when force downgrade to 8.6.0**
[success_version_log.txt](https://github.com/paketo-buildpacks/bellsoft-liberica/files/7229212/success_version_log.txt)

   I think JVM Option changes after BuildPack 8.7.0 cause error.
   I checked **_UnlockDiagnosticVMOptions NativeMemoryTracking PrintNMTStatistics_** options are added
   And  I've tried set docker env or gradle build option with JAVA_TOOL_OPTIONS to disable those things. But not works.

  **So, I forced downgrade builderpack version to 8.6.0 and it works.**
  ```
  bootBuildImage {
    builder = "paketobuildpacks/builder@sha256:3c5f88e55da475957bd03b4d6e852e0938bb73ee1a5184ae291a7566ca83d97f"
    runImage = "paketobuildpacks/run@sha256:562ddd10160a2629168a0108894766b46dff7f4b0db263ecabe35cd56fcbe56d"
  }
  ```

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
No Customs

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
**Simple docker image build with run `./gradlew bootBuildImage` with Spring Boot project in Github Action.**
**And Simple launch with Docker `docker run [built-image]`**
  ```yml
  name: ci
  
  on:
    push:
      branches:
        - 'release'
  
  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build bootBuildImage with version
          run: ./gradlew bootBuildImage
  ```

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.
