### ISSUE TITLE
Support JDK 16

### ISSUE THREAD

**Issue by IraRe** [paketo-buildpacks/bellsoft-liberica#86]
## What happened?

* What were you attempting to do?
I updated the Java version to 16 and want to use maven 3.6.3 with OpenJDK 16 to build the image by 
```
mvn spring-boot:build-image
```

* What did you expect to happen?
The expected behaviour is an image being built.

* What was the actual behavior? Please provide log output, if possible.
The goal failed with the error
```
Paketo BellSoft Liberica Buildpack 7.0.1
Step #1 - "build image": [INFO]     [creator]       unable to find dependency
Step #1 - "build image": [INFO]     [creator]       no valid dependencies for jdk, 16.*, and io.buildpacks.stacks.bionic in [(jdk, 8.0.282, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jre, 8.0.282, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jdk, 11.0.10, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jre, 11.0.10, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jdk, 15.0.2, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jre, 15.0.2, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3]) (jvmkill, 1.16.0, [io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3])]
```

## Build Configuration
I use Cloud Build with following configuration:
```
steps:
  - id: test
    name: maven:3.6.3-openjdk-16-slim
    entrypoint: mvn
    args:
      - verify
  - id: build image
    name: maven:3.6.3-openjdk-16-slim
    entrypoint: mvn
    args:
      - spring-boot:build-image
```

Similar issue was reported and solved for JDK 15: https://github.com/paketo-buildpacks/bellsoft-liberica/issues/14
